### ISSUE TITLE
Doesn't work....

### ISSUE THREAD

**Issue by Glathrop** [TaskTerminator/task-terminator#246]
Everything's broken!

**Comment by SJTreadway** [comment]
It's all your fault.

**Comment by Glathrop** [comment]
Still not working.

**Comment by johnazre** [comment]
Ummmmmm, AngularJS is SO two years ago...

**Comment by Glathrop** [comment]
We only use jQuery because... hipster vintage.

**Comment by Glathrop** [comment]
I don't think @SJTreadway is ever going to fix this.

**Comment by Glathrop** [comment]
Why is no one fixing this POS?
